# -*- coding: utf-8 -*- #
# Copyright 2025 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This file is autogenerated and should not be edited by hand.
# AUTOGEN_CLI_VERSION: HEAD
"""Single store for all your application parameters."""

from googlecloudsdk.calliope import base
from surface.parametermanager import _init_extensions as extensions


@base.ReleaseTracks(base.ReleaseTrack.BETA)
@base.Autogenerated
@base.Hidden
class ParametermanagerBeta(extensions.ParametermanagerBeta):
  """Parameter Manager is a single source of truth to store, access and manage the lifecycle of your application parameters.

  Parameter Manager aims to make management of sensitive application parameters
  effortless for customers without diminishing focus on security.
  """


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
class ParametermanagerGa(extensions.ParametermanagerGa):
  """Parameter Manager is a single source of truth to store, access and manage the lifecycle of your application parameters.

  Parameter Manager aims to make management of sensitive application parameters
  effortless for customers without diminishing focus on security.
  """
