name: CI

on:
  push:
    branches:
      - main
      - ci-test
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Run tests with coverage
        run: |
          echo "'Tests' job: go test"
          go test -cover ./...
