name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run tests
        run: go test ./... -cover

  Style:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Check formatting
        run: test -z $(go fmt ./...)
